/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Person;

import Business.Business;
import Business.Organisation.Organisation;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;

/**
 *
 * @author Abhishek
 */
public class ViewStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewStatusJPanel
     */
    private JPanel container;
    private Business business;
    private String id;
    public ViewStatusJPanel(JPanel container, Business business,String id) {
        initComponents();
        this.container=container;
        this.business=business;
        this.id=id;
        displayDetails();
    }
    
    private void displayDetails()
    {
        for(Organisation organization: business.getOrganisationDirectory().getOrganizationList())
        {
            for(WorkRequest workRequest: organization.getWorkQueue().getWorkRequestList())
            {
                if(workRequest.getCount().equals(id))
                {
                    workRequest.getStatus();
                     jLabel1.setText("Your request has been "+workRequest.getStatus());
                     
                    
                }
                else{
                    jLabel1.setText("Cannot find matching Request ID");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
